# plot the decoding time of each citrine

library("fields")

setwd("../../data/codon_scores/")


coeffs <- read.delim("weinberg_coef_200.txt", header = T) # from Amanda running Choros on weinberg data, June 2022

# sequences of individual citrine constructs
citMin_seq <- "ATGTCCAAAGGCGAAGAACTCTTTACCGGCGTCGTCCCCATTCTCGTCGAACTCGATGGCGATGTCAATGGCCACAAATTTTCCGTCTCCGGCGAAGGCGAAGGCGATGCCACCTATGGCAAACTCACCCTCAAATTTATTTGTACCACCGGCAAACTCCCCGTCCCCTGGCCCACCCTCGTCACCACCCTCGGCTATGGCCTCATGTGTTTTGCCCGTTATCCCGATCACATGAAACAACACGATTTTTTTAAATCCGCCATGCCCGAAGGCTATGTCCAAGAACGTACCATTTTTTTTAAAGATGATGGCAATTATAAAACCCGTGCCGAAGTCAAATTTGAAGGCGATACCCTCGTCAATCGTATTGAACTCAAAGGCATTGATTTTAAAGAAGATGGCAATATTCTCGGCCACAAACTCGAATATAATTATAATTCCCACAATGTCTATATTATGGCCGATAAACAAAAAAATGGCATTAAAGTCAATTTTAAAATTCGTCACAATATTGAAGATGGCTCCGTCCAACTCGCCGATCACTATCAACAAAATACCCCCATTGGCGATGGCCCCGTCCTCCTCCCCGATAATCACTATCTCTCCTATCAATCCGCCCTCTCCAAAGATCCCAATGAAAAACGTGATCACATGGTCCTCCTCGAATTTGTCACCGCCGCCGGCATTACCCACGGCATGGATGAACTCTATAAATGA"
cit0_seq <-   "ATGAGTAAAGGCGAAGAATTATTTACTGGCGTCGTCCCTATCCTAGTCGAACTAGACGGGGACGTCAATGGACACAAATTTTCCGTATCCGGCGAGGGGGAAGGCGACGCAACTTATGGGAAACTCACACTCAAATTTATATGTACCACCGGCAAACTACCCGTGCCTTGGCCCACTTTGGTCACCACACTAGGATACGGCCTCATGTGCTTCGCTAGATACCCGGACCACATGAAACAGCACGATTTTTTCAAGTCGGCAATGCCAGAAGGATATGTCCAGGAACGCACCATCTTCTTCAAAGATGATGGGAACTATAAAACGAGAGCTGAAGTAAAATTTGAAGGGGATACTCTCGTGAATCGTATAGAACTCAAAGGGATCGACTTTAAAGAAGATGGAAACATTCTGGGTCATAAGTTGGAGTACAACTACAACTCACATAACGTCTACATCATGGCGGACAAGCAGAAGAATGGCATCAAAGTCAATTTTAAAATTAGGCACAATATTGAAGACGGGTCCGTACAACTCGCTGATCACTATCAGCAAAACACTCCAATCGGCGACGGGCCAGTGCTACTCCCCGACAATCATTATTTATCCTATCAATCGGCTCTATCTAAAGACCCAAACGAAAAACGTGACCACATGGTACTCCTTGAATTTGTAACTGCCGCCGGCATCACACACGGCATGGATGAGCTTTATAAGTGA"
cit3_seq <-   "ATGAGCAAAGGCGAAGAGTTGTTTACCGGGGTGGTTCCGATACTTGTGGAATTAGACGGCGACGTCAATGGCCACAAATTTTCTGTTTCCGGTGAGGGGGAGGGGGATGCGACTTACGGCAAACTTACGTTAAAATTTATCTGTACAACGGGGAAATTGCCAGTGCCCTGGCCCACTCTGGTTACGACATTAGGATACGGACTGATGTGTTTCGCTCGCTATCCTGACCACATGAAACAGCACGATTTTTTTAAGAGCGCGATGCCTGAGGGTTACGTACAGGAGAGAACTATCTTCTTCAAAGATGATGGCAACTATAAAACTAGAGCTGAGGTGAAATTTGAGGGCGACACGCTCGTCAACAGGATTGAGCTAAAGGGTATAGATTTTAAGGAAGATGGGAACATTTTAGGACATAAGCTGGAGTACAACTACAACTCTCACAATGTATATATAATGGCTGACAAACAGAAGAATGGCATCAAGGTTAACTTCAAAATCAGGCACAACATCGAAGACGGGAGTGTACAACTAGCCGATCACTATCAGCAGAACACACCCATAGGTGACGGCCCTGTCTTGCTACCGGACAATCACTACCTATCTTATCAAAGTGCATTATCGAAGGACCCTAATGAAAAGAGAGACCACATGGTTCTGCTCGAGTTTGTCACTGCTGCAGGTATCACTCATGGGATGGACGAGTTATATAAATGA"
cit6_seq <-   "ATGAGTAAGGGAGAAGAACTATTTACCGGTGTCGTGCCGATTCTAGTAGAACTGGACGGAGATGTCAACGGACATAAATTCAGTGTAAGCGGTGAGGGCGAGGGCGATGCCACGTATGGGAAGCTGACGCTCAAGTTTATATGCACAACCGGGAAATTACCTGTCCCTTGGCCCACACTCGTTACTACATTAGGGTACGGATTGATGTGCTTTGCTAGGTACCCTGATCATATGAAGCAGCATGACTTTTTTAAAAGTGCAATGCCGGAGGGATATGTACAAGAACGCACTATATTCTTTAAAGATGACGGCAACTATAAAACACGTGCAGAGGTAAAGTTTGAAGGGGATACATTAGTCAATCGTATTGAACTGAAAGGTATAGACTTTAAGGAAGACGGGAACATCTTGGGTCACAAGCTCGAGTACAATTATAACTCCCATAACGTCTACATTATGGCGGATAAACAGAAGAATGGTATAAAAGTGAACTTCAAGATTAGGCACAACATTGAAGACGGGTCGGTGCAGCTGGCAGATCACTATCAACAGAACACGCCGATTGGGGATGGTCCAGTGTTACTCCCCGACAATCATTACCTCTCTTACCAGTCTGCTCTATCTAAGGACCCCAACGAAAAGAGGGATCATATGGTCTTGTTAGAATTCGTTACAGCCGCGGGGATTACACATGGAATGGATGAGTTGTATAAGTGA"
cit9_seq <-   "ATGTCTAAGGGTGAGGAGCTGTTCACAGGTGTTGTGCCCATCTTGGTGGAACTGGATGGAGATGTCAACGGCCACAAGTTTTCGGTTTCGGGAGAAGGTGAAGGAGACGCCACATACGGTAAGTTAACTCTTAAGTTCATCTGTACGACTGGAAAACTACCGGTCCCATGGCCGACACTTGTAACGACGCTAGGATATGGGTTAATGTGTTTTGCACGTTATCCAGACCATATGAAACAGCATGATTTTTTTAAATCGGCAATGCCCGAGGGTTATGTGCAGGAGAGGACAATATTTTTTAAGGACGATGGAAATTACAAAACACGAGCAGAAGTTAAATTCGAAGGTGATACCCTTGTTAATCGAATTGAACTTAAAGGGATAGACTTCAAGGAAGATGGTAACATACTGGGTCATAAGCTAGAATATAATTATAACAGCCATAACGTGTATATTATGGCGGATAAGCAGAAAAACGGTATTAAGGTCAACTTTAAAATTCGACATAACATCGAGGATGGCAGTGTTCAACTAGCAGATCACTATCAACAGAACACGCCGATCGGGGATGGGCCGGTCTTACTGCCGGACAATCATTATCTATCTTACCAGAGCGCGTTAAGCAAAGACCCGAATGAGAAGCGAGATCACATGGTCTTACTCGAGTTCGTTACGGCAGCGGGTATCACACATGGAATGGACGAGTTGTATAAGTGA"
citMax_seq <- "ATGAGCAAGGGGGAGGAGCTGTTCACGGGGGTGGTGCCGATACTGGTGGAGCTGGACGGGGACGTGAACGGGCATAAGTTCAGCGTGAGCGGGGAGGGGGAGGGGGACGCAACGTACGGGAAGCTGACGCTGAAGTTCATATGCACGACGGGGAAGCTGCCGGTGCCGTGGCCGACGCTGGTGACGACGCTGGGGTACGGGCTGATGTGCTTCGCACGATACCCGGACCATATGAAGCAGCATGACTTCTTCAAGAGCGCAATGCCGGAGGGGTACGTGCAGGAGCGAACGATATTCTTCAAGGACGACGGGAACTACAAGACGCGAGCAGAGGTGAAGTTCGAGGGGGACACGCTGGTGAACCGAATAGAGCTGAAGGGGATAGACTTCAAGGAGGACGGGAACATACTGGGGCATAAGCTGGAGTACAACTACAACAGCCATAACGTGTACATAATGGCAGACAAGCAGAAGAACGGGATAAAGGTGAACTTCAAGATACGACATAACATAGAGGACGGGAGCGTGCAGCTGGCAGACCATTACCAGCAGAACACGCCGATAGGGGACGGGCCGGTGCTGCTGCCGGACAACCATTACCTGAGCTACCAGAGCGCACTGAGCAAGGACCCGAACGAGAAGCGAGACCATATGGTGCTGCTGGAGTTCGTGACGGCAGCAGGGATAACGCATGGGATGGACGAGCTGTACAAGTGA"

# function to convert string to vector of codons
codonify <- function(str) { substring(str, seq(1, nchar(str), 3), seq(3, nchar(str), 3)) }

citMin <- codonify(citMin_seq)
cit0 <- codonify(cit0_seq)
cit3 <- codonify(cit3_seq)
cit6 <- codonify(cit6_seq)
cit9 <- codonify(cit9_seq)
citMax <- codonify(citMax_seq)

# codon decoding times: high number -> more footprints -> slower

# A site coefficients from Amanda's choros model run on the Weinberg data
# coefficients from choros are logs - exponentiate
asite <- exp(coeffs$estimate)
names(asite) <- sub("^A", "", coeffs$name) # coefficient names are all Axxx (A stands for A site)

asite <- asite[ sort(names(asite)) ]

citMin.speeds <- asite[citMin]
cit0.speeds <- asite[cit0]
cit3.speeds <- asite[cit3]
cit6.speeds <- asite[cit6]
cit9.speeds <- asite[cit9]
citMax.speeds <- asite[citMax]

speeds <- cbind(citMax.speeds, cit9.speeds, cit6.speeds, cit3.speeds, cit0.speeds, citMin.speeds)
speeds <- speeds[1:238,] # remove stop codon

cols <- colorRampPalette(c("white", "blue"))(128)[1:64] # just use the lighter blue part of this palette
citrinecols <- c( citmin = "magenta3", cit0 = "royalblue2", cit3 = "green3", cit6 = "gold1", cit9 = "darkorange2", citmax = "red2")


pdf("citrines2.pdf", width = 3.5, height = 1, pointsize = 6.5, useDingbats = F, bg = "white" )
par( mex = 0.65 ) # sets margin stuff
par( mar = c(7,6,2,2) )
par( oma = c(0,0.5,1,0) )
par( xpd = NA )
image( x = 1:238, y = 1:6, 
       z = speeds, 
       zlim = range(speeds),
       col = cols,
       xlab = "codon position",
       ylab = NA,
       axes = F
)
axis(1, lwd = 0, lwd.ticks = 0.75)
axis(2, lwd = 0, line = 1, lwd.ticks = 0, labels = rev(c("fastest", "slowest")), at = c(1,6), las = 1)
par( xpd = NA )
imagePlot( legend.only=TRUE, 
           zlim = range(speeds), 
           col=cols, horizontal=T, 
           smallplot = c(0.875, 0.95, 0.3, 0.35),
           legend.lab = "dwell time (au)",
           axis.args = list ( lwd = 0, lwd.ticks = 0.75, at = c(1, 2), 
                              tcl = -0.3, mgp = c(3, 0.5, 0))
)
par( xpd = NA )
points( rep(-5, 6), 1:6, pch = 20, col = rev(citrinecols))
dev.off()